<a href="https://colab.research.google.com/github/Gerenzeo/data_science_module_1/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
vector_1 = np.array([1, 2, 3, 4, 5], dtype=int)
print(vector_1)

[1 2 3 4 5]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
matrix_3x3 = np.array([[0, 0, 0],
                       [0, 0, 0],
                       [0, 0, 0]])
print(matrix_3x3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
matrix_5x5 = np.random.uniform(1, 11, (5, 5)).astype(int)
print(matrix_5x5)

[[ 6  3  9 10  7]
 [ 4  3  5  6  7]
 [ 5  6  4  9  3]
 [ 4  9  2 10  3]
 [ 8  5  2  7  4]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
matrix_4x4 = np.random.random((4, 4))
print(matrix_4x4)

[[0.01035014 0.74949063 0.9394697  0.01186256]
 [0.56748847 0.94362324 0.89483104 0.82904564]
 [0.91925909 0.37999223 0.19126381 0.77174199]
 [0.25157432 0.21056804 0.30961957 0.80014305]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
array_1 = np.random.uniform(1, 11, (5)).astype(int)
array_2 = np.random.uniform(1, 11, (5)).astype(int)

value = 10

print(array_1)
print(array_1 + value)
print(array_1 - value)
print(array_1 * value)
print(array_1 / value)

[10  7  8  2  1]
[20 17 18 12 11]
[ 0 -3 -2 -8 -9]
[100  70  80  20  10]
[1.  0.7 0.8 0.2 0.1]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
vector_1 = np.array([1, 3, 5, 7, 9, 11, 13])
vector_2 = np.array([2, 4, 6, 8, 10, 12, 14])

print(np.dot(vector_1, vector_2))

504


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
matrix_2x2 = np.random.uniform(1, 11, (2, 2)).astype(int)
matrix_2x3 = np.random.uniform(1, 11, (2, 3)).astype(int)


print(np.dot(matrix_2x2, matrix_2x3))

[[1 6]
 [2 7]]
[[ 4 10  4]
 [ 9  3  8]]
[[58 28 52]
 [71 41 64]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
matrix_3x3 = np.random.uniform(1, 11, (3, 3)).astype(int)

print("Current matrix")
print(matrix_3x3, "\n")
print("Invert matrix")
print(np.linalg.inv(matrix_3x3))



Current matrix
[[ 4  3 10]
 [ 6  7  7]
 [ 1  8  8]] 

Invert matrix
[[ 0.          0.19512195 -0.17073171]
 [-0.14285714  0.07665505  0.11149826]
 [ 0.14285714 -0.1010453   0.03484321]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
matrix_4x4 = np.random.uniform(0, 1, (4, 4))

print(matrix_4x4)
print("\n")
transported_matrix = np.transpose(matrix_4x4)
print(transported_matrix)

[[0.49500422 0.63173309 0.44953616 0.55674991]
 [0.21559315 0.97655532 0.22522833 0.30421327]
 [0.07601681 0.26194444 0.73899822 0.42650531]
 [0.01633835 0.90706192 0.71362999 0.35836191]]


[[0.49500422 0.21559315 0.07601681 0.01633835]
 [0.63173309 0.97655532 0.26194444 0.90706192]
 [0.44953616 0.22522833 0.73899822 0.71362999]
 [0.55674991 0.30421327 0.42650531 0.35836191]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
matrix_3x4 = np.random.uniform(1, 11, (3, 4)).astype(int)
vector_1 = np.random.randint(1, 11, size=4).astype(int)
print(matrix_3x4 * vector_1)

[[40 24  4 40]
 [30 24 16 90]
 [20 48 10 20]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
matrix_2x3 = np.random.rand(2, 3)
vector_1 = np.random.rand(3)
print(matrix_2x3 * vector_1)

[[0.60630659 0.10859619 0.62750096]
 [0.6951436  0.15998075 0.5043108 ]]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
matrix_1_2x2 = np.random.uniform(1, 11, (2, 2)).astype(int)
matrix_2_2x2 = np.random.uniform(1, 11, (2, 2)).astype(int)

print(matrix_1_2x2 * matrix_2_2x2)


[[  9  45]
 [100   4]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
matrix_1_2x2 = np.random.uniform(1, 11, (2, 2)).astype(int)
matrix_2_2x2 = np.random.uniform(1, 11, (2, 2)).astype(int)

print(np.dot(matrix_1_2x2, matrix_2_2x2))

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.


In [ ]:
matrix_5x5 = np.random.uniform(1, 101, (5, 5)).astype(int)
print(matrix_5x5.sum())

1228


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.



In [ ]:
matrix_1_4x4 = np.random.randint(1, 11, (4, 4))
matrix_2_4x4 = np.random.randint(1, 11, (4, 4))

print(matrix_1_4x4 - matrix_2_4x4)


[[ 0 -3  8  4]
 [ 4 -4 -2  1]
 [-7  3 -5  6]
 [-2 -2  1  1]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
matrix_3x3 = np.random.rand(3, 3)
print(matrix_3x3)

print("\n")
row_sums = np.sum(matrix_3x3, axis=1)
print(row_sums.reshape(3, 1))

[[0.68390387 0.20336159 0.18227348]
 [0.80017571 0.60981974 0.43033103]
 [0.84604691 0.82863245 0.99569808]]


[[1.06953894]
 [1.84032647]
 [2.67037744]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел

In [ ]:
matrix_1_3x4 = np.random.randint(1, 11, (3, 4))
matrix_pow_3x4 = np.square(matrix_1_3x4)


# print(matrix_1_3x4 ** 2)
print(matrix_1_3x4)
print('\n')
print(matrix_pow_3x4)

[[ 5 10  3  2]
 [ 1  3  1  2]
 [10  9  3  7]]


[[ 25 100   9   4]
 [  1   9   1   4]
 [100  81   9  49]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
vector_1 = np.random.randint(1, 51, size=4)

print(f"Current: {vector_1}")
print(f"Sqrt: {np.sqrt(vector_1)}")

Current: [39 46 34 42]
Sqrt: [6.244998   6.78232998 5.83095189 6.4807407 ]
